### ISSUE TITLE
Fails to run because of Webpack error

### ISSUE THREAD

**Issue by NetOpWibby** [mvlabs/isomorphic-mithril#2]
I downloaded, ran `npm i`, `npm start`, and this is what I got:

```error
> webpack --mode=development --watch

~/isomorphic-mithril-master/node_modules/webpack-cli/bin/config-yargs.js:89
				describe: optionsSchema.definitions.output.properties.path.description,
				                                           ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (~/isomorphic-mithril-master/node_modules/webpack-cli/bin/config-yargs.js:89:48)
    at ~/isomorphic-mithril-master/node_modules/webpack-cli/bin/webpack.js:60:27
    at Object.<anonymous> (~/isomorphic-mithril-master/node_modules/webpack-cli/bin/webpack.js:515:3)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:659:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```

I intend on swapping Webpack for rollup anyway but I wanted to bring this to your attention.

EDIT: Linting also fails.

**Comment by NetOpWibby** [comment]
[This answer](https://stackoverflow.com/a/52795175/1167646) fixed the Webpack issue.
